spring:
  profiles: dev
  application:
    name: register-server
eureka:
  instance:
    prefer-ip-address:  false  #不将自己的ip地址注册到Eureka服务中，而是使用主机名
    ip-address: 127.0.0.1
    instance-id: eureka-8001 #指定实例id
    hostname: eureka-8001.com #eureka实例的主机名
  client:
    register-with-eureka: true #把eureka注册进注册中心
    fetch-registry: true #获取注册信息
    service-url:
      defaultZone: http://eureka-8002.com:8002/eureka #此处用驼峰格式
  server:
    enable-self-preservation: true #禁用自我保护模式
    eviction-interval-timer-in-ms: 6000 #清理间隔（单位毫秒，默认是60*1000）
  eureka-server-connect-timeout-seconds: 10  
---
spring:
  profiles: test
  application:
    name: register-server